// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: user.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TeamServiceRPC_GetUserProfile_FullMethodName  = "/userservice_v1.TeamServiceRPC/GetUserProfile"
	TeamServiceRPC_GetUserProfiles_FullMethodName = "/userservice_v1.TeamServiceRPC/GetUserProfiles"
)

// TeamServiceRPCClient is the client API for TeamServiceRPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TeamServiceRPCClient interface {
	GetUserProfile(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserProfileResponse, error)
	GetUserProfiles(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserProfileResponse, error)
}

type teamServiceRPCClient struct {
	cc grpc.ClientConnInterface
}

func NewTeamServiceRPCClient(cc grpc.ClientConnInterface) TeamServiceRPCClient {
	return &teamServiceRPCClient{cc}
}

func (c *teamServiceRPCClient) GetUserProfile(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserProfileResponse)
	err := c.cc.Invoke(ctx, TeamServiceRPC_GetUserProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teamServiceRPCClient) GetUserProfiles(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserProfileResponse)
	err := c.cc.Invoke(ctx, TeamServiceRPC_GetUserProfiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TeamServiceRPCServer is the server API for TeamServiceRPC service.
// All implementations must embed UnimplementedTeamServiceRPCServer
// for forward compatibility.
type TeamServiceRPCServer interface {
	GetUserProfile(context.Context, *GetUserRequest) (*GetUserProfileResponse, error)
	GetUserProfiles(context.Context, *GetUserRequest) (*GetUserProfileResponse, error)
	mustEmbedUnimplementedTeamServiceRPCServer()
}

// UnimplementedTeamServiceRPCServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTeamServiceRPCServer struct{}

func (UnimplementedTeamServiceRPCServer) GetUserProfile(context.Context, *GetUserRequest) (*GetUserProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserProfile not implemented")
}
func (UnimplementedTeamServiceRPCServer) GetUserProfiles(context.Context, *GetUserRequest) (*GetUserProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserProfiles not implemented")
}
func (UnimplementedTeamServiceRPCServer) mustEmbedUnimplementedTeamServiceRPCServer() {}
func (UnimplementedTeamServiceRPCServer) testEmbeddedByValue()                        {}

// UnsafeTeamServiceRPCServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TeamServiceRPCServer will
// result in compilation errors.
type UnsafeTeamServiceRPCServer interface {
	mustEmbedUnimplementedTeamServiceRPCServer()
}

func RegisterTeamServiceRPCServer(s grpc.ServiceRegistrar, srv TeamServiceRPCServer) {
	// If the following call pancis, it indicates UnimplementedTeamServiceRPCServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TeamServiceRPC_ServiceDesc, srv)
}

func _TeamServiceRPC_GetUserProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeamServiceRPCServer).GetUserProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TeamServiceRPC_GetUserProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeamServiceRPCServer).GetUserProfile(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeamServiceRPC_GetUserProfiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeamServiceRPCServer).GetUserProfiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TeamServiceRPC_GetUserProfiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeamServiceRPCServer).GetUserProfiles(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TeamServiceRPC_ServiceDesc is the grpc.ServiceDesc for TeamServiceRPC service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TeamServiceRPC_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "userservice_v1.TeamServiceRPC",
	HandlerType: (*TeamServiceRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserProfile",
			Handler:    _TeamServiceRPC_GetUserProfile_Handler,
		},
		{
			MethodName: "GetUserProfiles",
			Handler:    _TeamServiceRPC_GetUserProfiles_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
